### ISSUE TITLE
could you send the trained model for me?

### ISSUE THREAD

**Issue by xuxiuzhi2627** [harryhan618/SCNN_Pytorch#11]
I can not open your link, could you send the trained model for me?my email address is 2627084603@qq.com
    Thank you

**Comment by harryhan618** [comment]
Uploaded to Baidu cloud.
vgg_SCNN_DULR_w9.pth: https://pan.baidu.com/s/1rVBErUBAFLZTkrrxARi3nw password: nmbi
Tusimple pretrained model: https://pan.baidu.com/s/1T8vWIC1Vz7PVnm_KkWG4wg password: 8rgi
CULane pretrained model: https://pan.baidu.com/s/1ulFI2Lj5X0R8uPEF9-vN0A password: 4q2y

**Comment by xuxiuzhi2627** [comment]
Thank you for your reply.Are you an chinese？



---Original---

**Comment by harryhan618** [comment]
Yes.

**Comment by xuxiuzhi2627** [comment]
Thank you very much I want know the version of cuda ?



---Original---

**Comment by harryhan618** [comment]
I remember pytorch 1.0+ requires cuda 9.0.

**Comment by xuxiuzhi2627** [comment]
ok，Ihave a try.Thank you for your reply

---Original---

**Comment by xuxiuzhi2627** [comment]
I have a problem.Please help me .look at the appendix.

---Original---

**Comment by xuxiuzhi2627** [comment]
Can you tell me how long it takes for your GPU model to train?




---Original---

**Comment by harryhan618** [comment]
It depends on how many GPUs you have. Typically running a training epoch with two 1080Ti is more than 3 hours. The bottleneck would be I/O if you have more GPUs.

**Comment by xuxiuzhi2627** [comment]
thank you.I meet a peoblem when I run the the code in the following picture.Do you know how to solve it?please look at the appendix.

---Original---

**Comment by harryhan618** [comment]
No appendix presented. Plz dig into your problem and try to solve it alone. Sorry I don't have that much time.

**Comment by xuxiuzhi2627** [comment]
Ok，thank you&nbsp;



---Original---
