### ISSUE TITLE
No module named 'utils.prob2lines'

### ISSUE THREAD

**Issue by xuxiuzhi2627** [harryhan618/SCNN_Pytorch#13]
ubuntu@141780e5a2f8:~/user_space/SCNN_Pytorch-master$ python demo_test.py -i demo/demo.jpg -w experiments/vgg_SCNN_DULR_w9/vgg_SCNN_DULR_w9.pth [--visualize / -v]
Traceback (most recent call last):
  File "demo_test.py", line 18, in <module>
    from utils.prob2lines import getLane
ImportError: No module named 'utils.prob2lines'

**Comment by harryhan618** [comment]
I think my code struncture is quite clear. You can find `getLane.py` in `utils/prob2lines`.
