### ISSUE TITLE
what are the anno_dir and detection_dir?

### ISSUE THREAD

**Issue by xuxiuzhi2627** [harryhan618/SCNN_Pytorch#14]
the directory in /utils/lane_evaluation/CULane/src/evaluate.cpp, which  directory should  I  write about anno_di, detection_dir  and im_dir ?

**Comment by harryhan618** [comment]
Please use `utils/lane_evaluation/CULane/Run.sh` as reference.

**Comment by xuxiuzhi2627** [comment]
Thank you!You are a great man



---Original---
