### ISSUE TITLE
Will the sequence of SCNN_D, SCNN_U, SCNN_R, SCNN_L effect the performance？

### ISSUE THREAD

**Issue by chixma** [harryhan618/SCNN_Pytorch#16]
Thanks for sharing the codes! I have a question about the algorithm. As the lanes in the datasets usually appear in a vertical-like mode, I am not sure whether the sequence of SCNN_D, SCNN_U, SCNN_R, SCNN_L effects the performance? Do you have any idea about it?

**Comment by harryhan618** [comment]
Good question! Actually, I haven't had time to dig into these details. As you read in the evaluation part in the paper, I think the critical procedure is `SCNN_D` and `SCNN_U` operation. But `SCNN_L` and `SCNN_R` directions do help improve the performance. If you have time, you can test it yourself. For example, get rid of `SCNN_L` and `SCNN_R`, or, replace  `SCNN_L` and `SCNN_R` with another `SCNN_D` and `SCNN_U`.
Feel free to share with me.
