### ISSUE TITLE
The Tusimple model accuracy

### ISSUE THREAD

**Issue by chixma** [harryhan618/SCNN_Pytorch#17]
@harryhan618  Hi, I evaluated the model that you provide on the Tusimple dataset by the test_tusimple.py. the result is as follows: 
[{"order": "desc", "value": 0.9416278328369392, "name": "Accuracy"}, {"order": "asc", "value": 0.073538221902708, "name": "FP"}, {"order": "asc", "value": 0.08252456266474979, "name": "FN"}]
Well, I find there is a mismatch with your reported results in the README. Do you have any idea about it? Thank you!

**Comment by harryhan618** [comment]
There was a bug in my evaluation code. I fixed the bug and re-evaluated my trained model on CULane. But I forget to re-evaluate the model on Tusimple. Thank you for updating!
