### ISSUE TITLE
problems with converting models

### ISSUE THREAD

**Issue by yiyayamaya** [harryhan618/SCNN_Pytorch#19]
Hi! Thanks for sharing!
When I run 
python experiments/vgg_SCNN_DULR_w9/t7_to_pt.py
I got 
Traceback (most recent call last):
  File "experiments/vgg_SCNN_DULR_w9/t7_to_pt.py", line 112, in <module>
    net = SCNN(pretrained=False)
TypeError: __init__() missing 1 required positional argument: 'input_size'
Can you help me?
My torch version is 0.4.1 and python version is 3.6. Thanks!

**Comment by harryhan618** [comment]
The code has been updated.

**Comment by yiyayamaya** [comment]
> The code has been updated.

It works! Thanks!
