### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by Tomingz** [harryhan618/SCNN_Pytorch#2]
你好，python3.6+pytorch0.4.1,运行demo_test.py出现错误，如何解决呀？

**Comment by harryhan618** [comment]
你能把运行错误结果发一下吗？描述太过模糊

**Comment by harryhan618** [comment]
> 你好，python3.6+pytorch0.4.1,运行demo_test.py出现错误，如何解决呀？

你能把运行错误结果发一下吗？描述太过模糊
