### ISSUE TITLE
the accuracy is 0 when I test your model

### ISSUE THREAD

**Issue by andeyeluguo** [harryhan618/SCNN_Pytorch#20]
the output is this:

[{"name": "Accuracy", "value": 0.0, "order": "desc"}, {"name": "FP", "value": 0.0, "order": "asc"}, {"name": "FN", "value": 1.0, "order": "asc"}]

I have no idea why this happens, I just run the code as your readme.

**Comment by harryhan618** [comment]
I just test it again. The result is in accord with what's reported in readme. Please follow the data preparation and test again. 
I also fix some bugs. You can pull the new code first.
