### ISSUE TITLE
What improvements have you made to improve the accuracy?

### ISSUE THREAD

**Issue by xuxiuzhi2627** [harryhan618/SCNN_Pytorch#21]
hello,could you tell me What improvements have you made to improve the accuracy?

**Comment by harryhan618** [comment]
I don't think the accuracy has been improve much. On CULane dataset, F1 measure may be higher than what's reported in the paper in some Category (e.g. Arrow), but there are drops as well. Maybe you can try with large batchsize.

**Comment by xuxiuzhi2627** [comment]
The normal road accuracy of  CULane is 87 when I test use your code,I have no idea to improve the accuracy.I want to achieve the  accuracy of your.




------------------ 原始邮件 ------------------
发件人: "MaybeShewill-CV"<notifications@github.com>;
发送时间: 2019年9月27日(星期五) 上午10:05
收件人: "harryhan618/SCNN_Pytorch"<SCNN_Pytorch@noreply.github.com>;
抄送: "2627084603"<2627084603@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [harryhan618/SCNN_Pytorch] What improvements have you made toimprove the accuracy? (#21)




I don't think the accuracy has been improve much. On CULane dataset, F1 measure may be higher than what's reported in the paper in some Category (e.g. Arrow), but there are drops as well. Maybe you can try with large batchsize.

**Comment by harryhan618** [comment]
Excuse me,  I didn't get your point. 
But first, please get the new code first since there are updates and several bugs are fixed.
