### ISSUE TITLE
替换backbone

### ISSUE THREAD

**Issue by TonyAlpha12** [harryhan618/SCNN_Pytorch#25]
大佬，你用的vgg16有在ImageNet上预训练吗？我把vgg16换成MobileNetV2（没有预训练），但是效果很差，不知道怎么改，有什么建议吗？

**Comment by harryhan618** [comment]
你好， 替换backbone只要把`model.py`里，self.backbone相应换掉就行了。 如果训练的话可能需要做更多调试才能找到比较好的超参配置。如果有预训练的模型迁移过来，应该会使得模型更容易训练。

**Comment by TonyAlpha12** [comment]
> 你好， 替换backbone只要把`model.py`里，self.backbone相应换掉就行了。 如果训练的话可能需要做更多调试才能找到比较好的超参配置。如果有预训练的模型迁移过来，应该会使得模型更容易训练。

我在Tusimple上训练了很多次，改变了MobileNet的结构，后面损失在1个epoch就稳定在0.15左右了，然后就降不下去，再往后直接梯度爆炸了，不知道是为什么

**Comment by harryhan618** [comment]
尝试把lr初始化小一点试试, 譬如1e-3级别的或者更小
如果有预训练的模型应该不容易梯度爆炸, pytorch官方有预训练的mobilenet_v2吧, https://pytorch.org/docs/stable/torchvision/models.html

**Comment by TonyAlpha12** [comment]
> 尝试把lr初始化小一点试试, 譬如1e-3级别的或者更小
> 如果有预训练的模型应该不容易梯度爆炸, pytorch官方有预训练的mobilenet_v2吧, https://pytorch.org/docs/stable/torchvision/models.html

好，我试试，谢谢大佬！

**Comment by TonyAlpha12** [comment]
> 尝试把lr初始化小一点试试, 譬如1e-3级别的或者更小
> 如果有预训练的模型应该不容易梯度爆炸, pytorch官方有预训练的mobilenet_v2吧, https://pytorch.org/docs/stable/torchvision/models.html

我把学习率设小了，已经OK了。我有一个疑问，就是Tusimple和CULane的训练集里，车道线都是这么宽的吗？模型验证的时候，看到分割出来的车道线比路面上的车道线宽不少，这个有办法解决吗，大佬？

**Comment by harryhan618** [comment]
在原图大小下，车道线的标注应该大概是30个pixel粗吧。 在测试的时候，你可以根据个人需求加入后处理，譬如提取每条车道线在每个y值的x坐标， 然后连起来这样。
话说mobilenet_v2怎么样？效果好嘛？速度快嘛？

**Comment by TonyAlpha12** [comment]
> 在原图大小下，车道线的标注应该大概是30个pixel粗吧。 在测试的时候，你可以根据个人需求加入后处理，譬如提取每条车道线在每个y值的x坐标， 然后连起来这样。
> 话说mobilenet_v2怎么样？效果好嘛？速度快嘛？

行，我试试。效果跟VGG16的差不多。我在1060上跑，224的输入，mobilenetv2要13ms，message passing 要12ms。弯道效果不是很好，这两个数据集里弯道的场景好像都不多

**Comment by ubill88** [comment]
@TonyAlpha12  @harryhan618 您好，小弟是新手，有試著把`model.py`中第88行換成`mobilenet_v2`
並且把`# -- process backbone --`這部分先拿掉，不過實際運行後因為Shape的問題報錯，您能否分享如何把Backbone置換呢? 非常感謝您!

**Comment by harryhan618** [comment]
@ubill88 Hello！我觉得这个问题比较基础，你可以多试试pytorch怎么用的，把backbone运行出来的feature map大小打印出来，就直到最后fully connected layer大小应该是多少了。
