### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by monsterlyg** [harryhan618/SCNN_Pytorch#26]
你好，请教下你自己训练的模型在CULane上最后损失大概在多少；我把初始学习率调整到5e-4 ，一个epoch之后基本已经不下降了，大概在0.14，我之前自己用tensorflow训练过TuSimple的训练集，用分割的交叉熵损失，最后也在0.05~0.1；但我不确定在CULane上损失可以降到多少？这两个训练集我用的都是自己搭的网络。

**Comment by harryhan618** [comment]
最终在10-2量级。比loss大小意义不太大吧？

**Comment by monsterlyg** [comment]
嗯 谢谢 了解一下
