### ISSUE TITLE
A train error on tusimple

### ISSUE THREAD

**Issue by ABexit** [harryhan618/SCNN_Pytorch#27]
Thanks for your sharing, there is a train error on tusimple, could you give me a hand? thanks again.
"/SCNN_Pytorch/utils/transforms/transforms.py", line 156, in __call__,
exist = torch.from_numpy(exist).type(torch.float32)  # BCEloss requires float tensor 
TypeError: expected np.ndarray (got list)"

**Comment by harryhan618** [comment]
Your information is too vague. What is your input for `transforms`? It seems you should make the input of `exist` be a numpy array.

**Comment by ABexit** [comment]
> Your information is too vague. What is your input for `transforms`? It seems you should make the input of `exist` be a numpy array.

Excause me, it seems that i changed something wrong. I have fixed it, thanks.

**Comment by lilyzhng** [comment]
@ABexit Hi, I have some issues with tusimple training, after train epoch #0, val epoch #1, it will always stuck at train epoch #1. Do you have the same problem?

**Comment by ABexit** [comment]
> @ABexit Hi, I have some issues with tusimple training, after train epoch #0, val epoch #1, it will always stuck at train epoch #1. Do you have the same problem?

Can you describe it detailly?

**Comment by harryhan618** [comment]
> @ABexit Hi, I have some issues with tusimple training, after train epoch #0, val epoch #1, it will always stuck at train epoch #1. Do you have the same problem?

Maybe it's related to your machine (GPU) error.

**Comment by lilyzhng** [comment]
@ABexit Thanks for the reply. I have opened a new issue here. https://github.com/harryhan618/SCNN_Pytorch/issues/32 you could find more detailed description here.

**Comment by lilyzhng** [comment]
@harryhan618 Could you explain why it will be a GPU error? I tried both on my local machine, and on hpc, it always stuck at epoch #1.

**Comment by lilyzhng** [comment]
@harryhan618 I realized that hpc I am using might not be able to do torch.nn.DataParallel, do you what I should I change it to?

**Comment by harryhan618** [comment]
@alchemz If you are familiar with `DistributedDataParallel`, maybe you could try this one. Your may refer to pytorch website or dig into mmdetection on github for how to use it.
