### ISSUE TITLE
Run demo_test.py on GPU

### ISSUE THREAD

**Issue by maym86** [harryhan618/SCNN_Pytorch#28]
Hello,

I am running the demo_test.py script successfully but it seems to be using the cpu.

I tried a few things including setting the map_location to cuda:

` save_dict = torch.load(weight_path, map_location='cuda') `

And setting the model to cuda() in model.py. But neither of these seem to make any difference.

Any ideas?

**Comment by maym86** [comment]
Figured it out

add `torch.set_default_tensor_type('torch.cuda.FloatTensor')` to the top of demo_test.py

and add .cuda() to this line in demo_test.py `def main()` around line 60 

```
x = transform_to_net({'img': img})['img'].cuda()
```

**Comment by vabrishami** [comment]
Hi @maym86. Can you please help me with running the demo on GPU? I did change what you suggested in your second comment, however, still, some errors are there. Should I also consider the proposed changes in your first comment? Thanks!

**Comment by maym86** [comment]
Try it. I can't remember tbh. Been a few years since I did this. Sorry.

**Comment by harryhan618** [comment]
@vabrishami Maybe you can change `map_location='cuda'` to `map_location='cpu'`.

**Comment by vabrishami** [comment]
Thanks @harryhan618 and @maym86. I made the following changes to make it work:

1- After net.eval() line, add a new line with net.cuda()
2- Change x = transform_to_net({'img': img})['img'].cpu() to x = transform_to_net({'img': img})['img'].cuda()

That's it. With these changes, I could run it on GPU.
