### ISSUE TITLE
Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same error when I tried to modify the code to gpu version?

### ISSUE THREAD

**Issue by masouduut94** [harryhan618/SCNN_Pytorch#29]
I created this lane_detection file and wrote this:

    import argparse
    import sys
    from time import time, clock
    from os.path import splitext, basename, exists
    
    from model import SCNN
    from utils.check_extension import is_video, is_image
    from utils.transforms import *
    
    
    # ------------------------------------------------  SCNN parameters
    time1 = time()
    net = SCNN(input_size=(800, 288), pretrained=False)
    mean = (0.3598, 0.3653, 0.3662)  # CULane mean, std
    std = (0.2573, 0.2663, 0.2756)
    transform_img = Resize((800, 288))
    transform_to_net = Compose(ToTensor(), Normalize(mean=mean, std=std))
    
    
    # ------------------------------------------------  Arguments
    
    
    def parse_args():
        parser = argparse.ArgumentParser()
    
        parser.add_argument('--weights', type=str,
                            default='models/vgg_SCNN_DULR_w9.pth',
                            help='path to vgg models')
    
        parser.add_argument('--input', type=str, default='demo/line_3.mp4',
                            help='path to image file')
    
        parser.add_argument('--output', type=str, default='public/',
                            help='path to the output directory')
        args = parser.parse_args()
    
        return args
    
    def main():
        args = parse_args()
        filename, extension = splitext(basename(args.input))
    
        print("Loading file [{}] ....".format(filename))
        if not exists(args.input):
            print("file [{}] is not recognized".format(args.input))
            sys.exit()

        if is_video(extension):
            video_capture = cv2.VideoCapture()
            fourcc = cv2.VideoWriter_fourcc(*'XVID')
            output = args.output + filename + '.avi'
    
            if video_capture.open(args.input):
                property_id = int(cv2.CAP_PROP_FRAME_COUNT)
                total_frames = int(cv2.VideoCapture.get(video_capture, property_id))
                frame_no = 1
                width, height = int(video_capture.get(cv2.CAP_PROP_FRAME_WIDTH)), \
                                int(video_capture.get(cv2.CAP_PROP_FRAME_HEIGHT))
                fps = video_capture.get(cv2.CAP_PROP_FPS)
                device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
                save_dict = torch.load(args.weights, map_location=device)
                net.load_state_dict(save_dict['net'])
                net.eval()
                net.to(device)
    
                # can't write out mp4, so try to write into an AVI file
                video_writer = cv2.VideoWriter(output, fourcc, fps, (width, height))
                while video_capture.isOpened():
                    start = time()
                    ret, frame = video_capture.read()
                    if not ret:
                        break
                    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                    frame = transform_img({'img': frame})['img']
                    x = transform_to_net({'img': frame})['img']
                    x.unsqueeze_(0)
    
                    stop1 = time()
                    print('stop1: ', stop1 - start)
    
                    seg_pred, exist_pred = net(x)[:2]
                    seg_pred = seg_pred.detach().cpu().numpy()
                    exist_pred = exist_pred.detach().cpu().numpy()
                    seg_pred = seg_pred[0]
    
                    stop2 = time()
                    print('stop2: ', stop2 - stop1)
    
                    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
                    lane_img = np.zeros_like(frame)
                    color = np.array([[255, 125, 0], [0, 255, 0], [0, 0, 255], [0, 255, 255]], dtype='uint8')
                    coord_mask = np.argmax(seg_pred, axis=0)
                    for i in range(0, 4):
                        if exist_pred[0, i] > 0.5:
                            lane_img[coord_mask == (i + 1)] = color[i]
                    img = cv2.addWeighted(src1=lane_img, alpha=0.8, src2=frame, beta=1., gamma=0.)
                    img = cv2.resize(img, (width, height))
    
                    stop3 = time()
                    print('stop3: ', stop3 - stop2)
    
                    # if frame_no % 20 == 0:
                    #     print('# {}/{} frames processed!'.format(frame_no, total_frames))
                    frame_no += 1
                    video_writer.write(img)
                    end = time()
                    print('Whole loop: {} seconds'.format(end - start))
                    print('------------')
                    print('------------')
    
                print('# All frames processed ')
    
                video_capture.release()
                video_writer.release()

        elif is_image(extension):
            img = cv2.imread(args.input)
            height, width, _ = img.shape
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
            img = transform_img({'img': img})['img']
            x = transform_to_net({'img': img})['img']
            x.unsqueeze_(0)
    
            save_dict = torch.load(args.weights, map_location='cpu')
            net.load_state_dict(save_dict['net'])
            net.eval()
    
            seg_pred, exist_pred = net(x)[:2]
            seg_pred = seg_pred.detach().cpu().numpy()
            exist_pred = exist_pred.detach().cpu().numpy()
            seg_pred = seg_pred[0]
    
            img = cv2.cvtColor(img, cv2.COLOR_RGB2BGR)
            lane_img = np.zeros_like(img)
            color = np.array([[255, 125, 0], [0, 255, 0], [0, 0, 255], [0, 255, 255]], dtype='uint8')
            coord_mask = np.argmax(seg_pred, axis=0)
            for i in range(0, 4):
                if exist_pred[0, i] > 0.5:
                    lane_img[coord_mask == (i + 1)] = color[i]
            img = cv2.addWeighted(src1=lane_img, alpha=0.8, src2=img, beta=1., gamma=0.)
            img = cv2.resize(img, (width, height))
            output = args.output + filename + '.jpg'
    
            cv2.imwrite(output, img)
    
        else:
            print("file format [{}] is not supported".format(args.input))
            sys.exit()
    
    
    if __name__ == '__main__':
        main()
    

And I got this error:

    Traceback (most recent call last):
      File "/home/gpu/codes/MSD/scnn_pytorch/lane_detection_server.py", line 157, in <module>
        main()
      File "/home/gpu/codes/MSD/scnn_pytorch/lane_detection_server.py", line 83, in main
        seg_pred, exist_pred = net(x)[:2]
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/gpu/codes/MSD/scnn_pytorch/model.py", line 32, in forward
        x = self.backbone(img)
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
        input = module(input)
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
        result = self.forward(*input, **kwargs)
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 345, in forward
        return self.conv2d_forward(input, self.weight)
      File "/home/gpu/anaconda3/envs/slow_fast/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 342, in conv2d_forward
        self.padding, self.dilation, self.groups)
    RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same

So how can I modify the code to be able to run the code on gpu machine? And if I be able to do so, Can I still use the weights `vgg_SCNN_DULR_w9.pth` for prediction or I have to train from scratch?

**Comment by harryhan618** [comment]
I think you forget to move data to gpu device.
```
frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
frame = transform_img({'img': frame})['img']
x = transform_to_net({'img': frame})['img']
x.unsqueeze_(0)
```
Here, you should add an additional line to move `x` to gpu. Be patient and double check you code.  :-)
