### ISSUE TITLE
About the experiments results

### ISSUE THREAD

**Issue by lHou157** [harryhan618/SCNN_Pytorch#3]
Hello，thank you for your sharing！ Could you please add some supplying about the experiments results such as accuracy or F1-measure and so on if possible，I have no idea about it and I have been stuck on this for many days. I really appreciate it if you could share your thought or ideas. Thank you again!

**Comment by harryhan618** [comment]
Sure. I would add evalution codes and descripion later these days. 
BTW, there's a revision in the network. Stay updated.

**Comment by lHou157** [comment]
Oh! Thank you very much! I am looking forward to your sharing! You are really a nice man!

**Comment by harryhan618** [comment]
There's an important change in the `model.py`. Please get updated.

**Comment by lHou157** [comment]
Oh！ Thank you very much and I will study it  carefully!

发送自 Windows 10 版邮件应用

发件人: HarryHan
发送时间: 2019年5月9日 11:45
收件人: harryhan618/SCNN_Pytorch
抄送: lHou157; Author
主题: Re: [harryhan618/SCNN_Pytorch] About the experiments results (#3)

There's an important change in the model.py. Please get updated.

**Comment by ZhiyuanChen** [comment]
> Sure. I would add evalution codes and descripion later these days.
> BTW, there's a revision in the network. Stay updated.

Hi, thank you very much for your work. I tried some images from TuSimple dataset and my own test images, however, it seems the nn cannot detect the lanes at all. Is there any issue with pre-trained model?

**Comment by harryhan618** [comment]
> > Sure. I would add evalution codes and descripion later these days.
> > BTW, there's a revision in the network. Stay updated.
> 
> Hi, thank you very much for your work. I tried some images from TuSimple dataset and my own test images, however, it seems the nn cannot detect the lanes at all. Is there any issue with pre-trained model?

The currently provided model is trained on CULane dataset. If you want to use it on other dataset or your images, you have to train the model on the corresponding dataset first. Tansfer issue is kind of a demerit of deep learning approach.

**Comment by ZhiyuanChen** [comment]
> > > Sure. I would add evalution codes and descripion later these days.
> > > BTW, there's a revision in the network. Stay updated.
> > 
> > 
> > Hi, thank you very much for your work. I tried some images from TuSimple dataset and my own test images, however, it seems the nn cannot detect the lanes at all. Is there any issue with pre-trained model?
> 
> The currently provided model is trained on CULane dataset. If you want to use it on other dataset or your images, you have to train the model on the corresponding dataset first. Tansfer issue is kind of a demerit of deep learning approach.

lol, thanks for replying. I thought this as a lane line detecor, would have good generalization ability.
