### ISSUE TITLE
the difference of the two "lane_width"?

### ISSUE THREAD

**Issue by Bonsen** [harryhan618/SCNN_Pytorch#33]
1、
In https://github.com/XingangPan/seg_label_generate/blob/master/src/main.cpp (line 37), the lane width of CULane is 16.
In https://github.com/harryhan618/SCNN_Pytorch/blob/master/dataset/Tusimple.py (line 153), the lane width of Tusimple is 15.
Do they need to be the same?

2、Why are the y_px_gap, pts in getLane.prob2lines_CULane/Tusimple different?

**Comment by harryhan618** [comment]
hello!
1. I remember the width of Tusimple dataset is 15. You can change it to 16 if you want. I don't think it will have much effect.
2. You can refer to [Tusimple evaluation code](https://github.com/TuSimple/tusimple-benchmark/blob/master/evaluate/lane.py), pts used is different from what's used in CULane's.

**Comment by Bonsen** [comment]
Thanks!
