### ISSUE TITLE
How to change the optimizer?

### ISSUE THREAD

**Issue by ubill88** [harryhan618/SCNN_Pytorch#34]
Hi, I'm a student and still very new to this field.
First of all, thanks for all the works you shared!
My problem is:
I was trying to change the optimizer from SGD to ADAM in train.py line 66.
I've also changed the cfg.file to the form that ADAM need (simply just delete the "momentum" & "nesterov").
It works just fine if I train from scratch.
However, it returns a Keyerror if I want to load the .pth file you provid and resume training.
` 
 File "/usr/local/lib/python3.6/dist-packages/torch/optim/adam.py", line 82, in step
    exp_avg, exp_avg_sq = state['exp_avg'], state['exp_avg_sq']
`
I found people sharing that it seems Pytorch can't change the optimizer if resuming the training process.
EX: https://github.com/pytorch/pytorch/issues/7499
Is it possible that I can resume the work you train on CULane dataset, and simply just change the optimizer?
Please give me some advice!
Thank you very mich!

**Comment by harryhan618** [comment]
It seems it's the problem of pytorch rather than my repo. Maybe you can print out the class type of the optimizer loaded from .pth file. This makes sure the type is indeed adam optimizer rather than sgd. Hope this will help.

**Comment by ubill88** [comment]
@harryhan618  Thank you very much!
