### ISSUE TITLE
Cannot get the same F-Score using the ckpt

### ISSUE THREAD

**Issue by FCInter** [harryhan618/SCNN_Pytorch#36]
I use your trained ckpt file to perform the test. The F-Score is very low, like 0.10. However, using the torch version ckpt, which is also provided in this repo, the F-Score is good.

Moreover, I train the model from scratch (with VGG preloaded), the best F-Score I can get is 0.78 for normal. For other test splits, the F-Score is 20%-50% lower than is reported in this repo and paper.

I'm quite sure that I did not modify anything in the code except the data path.

What's wrong with my reimplementation?

Thank you!!!

**Comment by harryhan618** [comment]
Sorry, I don't catch your point. What are these two ckpt files?
