### ISSUE TITLE
I met a question during training ,can you give me some advice ?

### ISSUE THREAD

**Issue by snowflake119** [harryhan618/SCNN_Pytorch#38]
size mismatch for fc.0.weight: copying a param with shape torch.Size([128, 4500]) from checkpoint, the shape in current model is torch.Size([128, 2880])
just as above,will you please give me some advice?

**Comment by harryhan618** [comment]
You see, the fc layer size is wrong. I think it's something to do with the config file. Your have to figure out what's the proper input size of the CNN model for your desired model.

**Comment by snowflake119** [comment]
thank you ,I have solved the above mentioned question,but there isn't output,just as below 
20-05-19 13:20:50.937773: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5648fde76dd0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-05-19 13:20:50.937792: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): GeForce GTX 1650, Compute Capability 7.5
or the train.py work?

**Comment by snowflake119** [comment]
python3 train.py --exp_dir ./experiments/exp10 -r
I run the code as above ,but it doesn't work!

**Comment by harryhan618** [comment]
Sorry, I don't know what happens to you.
