### ISSUE TITLE
how to convert pytorch model to caffe model?

### ISSUE THREAD

**Issue by snowflake119** [harryhan618/SCNN_Pytorch#42]
Dear sir :
     I have trained the scnn net ,now I want to convert the scnn pytorch model to caffe model ,I have no idea ,can you give me some advice ,thank you

**Comment by harryhan618** [comment]
Sorry, you are asking something that is unrelated to this repo. This repo has nothing to do with caffe. You have to figure out how to use caffe yourself. Good luck.
