### ISSUE TITLE
how to test CULane datasets

### ISSUE THREAD

**Issue by yuze9542** [harryhan618/SCNN_Pytorch#44]
I think the test_CULane code is not  incomplete. and I can not find CMakeLists.txt is provided... 
Can you help me? Thanks～

**Comment by harryhan618** [comment]
'not incomplete'? I think you are joking. lol
The c++ evaluation code is under `SCNN_Pytorch/utils/lane_evaluation/CULane/`. 
BTW, I just uploaded a multithreaded version. Keep Updated.

**Comment by yuze9542** [comment]
I’m sorry.I don’t understand how to use the code.I’m a newcomer&nbsp;



发自我的iPhone


------------------ Original ------------------

**Comment by harryhan618** [comment]
I don't know what's your question.
