### ISSUE TITLE
HI,Can you help me how to test CUlane data

### ISSUE THREAD

**Issue by yuze9542** [harryhan618/SCNN_Pytorch#45]
I don't know how to test CUlane dataset.because I don't understand why test dataset don't have label so that I how can test F1 score or recall rate or accuracy. Because i can't compute Loss.
I would appreciate it if someone could answer my question.

**Comment by harryhan618** [comment]
Sorry, I don't understand what you are talking about.
All the dataset images have label, including test part. You just need to follow Readme.md. I think it it quite automatic.
