### ISSUE TITLE
what cfgs used in training on CULane dataset?

### ISSUE THREAD

**Issue by zlxu2011** [harryhan618/SCNN_Pytorch#46]
Hi, Recently, when I test with model you provided on culane dataset, I found that the model has trained at least 13 epochs, but according cfg file from experiments/exp10, it will only training maximum 11 epochs [(L212),](https://github.com/harryhan618/SCNN_Pytorch/blob/master/train.py#L212) so can you tell me what cfgs you used in training on culane dataset? Besides, the lr (16e-2) is also a little bit large and will cause loss to be Nan.

**Comment by harryhan618** [comment]
The number of epoch doesn't really matter that much. I remember around 10k iterations would be fine. Also, I trained with 8 GPUs. So maybe you can set lr to 1e-2 or so.

**Comment by zlxu2011** [comment]
OK, I got it! Thank you for your reply.
