### ISSUE TITLE
Hi，i come from your lanenet,thanks for your great work.

### ISSUE THREAD

**Issue by HITjialanyu** [harryhan618/SCNN_Pytorch#5]
i use your code detect picture and video today, and per image(frame) ,it use 3 seconds.it seems different from  https://www.youtube.com/watch?v=ey5XPs1012k ,Is this work finished?Is it still missing the lane line quadratic function fitting? Thank  you。

**Comment by harryhan618** [comment]
It depends on what model you use to fit the lane. So yes, the lane fitting isn't in this repository. But this is finished work.

**Comment by HITjialanyu** [comment]
@harryhan618  Thank you. waiting for your next work!
