### ISSUE TITLE
请问怎么检测多于4条车道线?

### ISSUE THREAD

**Issue by norainnosun** [harryhan618/SCNN_Pytorch#50]
感谢您的开源,我看代码中是固定的四条车道线,并且是以当前车辆行驶车道为界分为左右两部分.如果数据集是摄像头采集的,并且要检测出图片中的所有车道线,这种情况下数据应该怎么标呢?是否是需要设置一个最大的车道线个数,比如10条,然后从左到右分别分配id,假如还要标注如下图中的导流线(整个导流线区域作为一个整体)是否应该将导流区域单独标注一个特别的id?谢谢!
![daoliu](https://user-images.githubusercontent.com/66993916/95645324-75d11e80-0af0-11eb-9c80-6465cbab4973.png)

**Comment by harryhan618** [comment]
我没有试过更多的车道线。如果想要检测更多车道线，可以按照你说的方法标注。
导流区域我不知道怎么处理，你有好想法吗？导流线可以分成独立的两根进行检测吧。

**Comment by norainnosun** [comment]
谢谢您的回复,导流线应该可以将两侧的车道线标记为导流线处理
