### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by HejhGitHub** [harryhan618/SCNN_Pytorch#54]
hello I found the mistake when I run.please help.Thanks 
RuntimeError: Error(s) in loading state_dict for SCNN:
        size mismatch for fc.0.weight: copying a param with shape torch.Size([128, 2880]) from checkpoint, the shape in current model is torch.Size([128, 4500]).

**Comment by harryhan618** [comment]
It seems you try to load tusimple model parameter state_dict to CULane's. The input shapes are different between these two datasets.

**Comment by HejhGitHub** [comment]
> 似乎您尝试将tusimple模型参数state_dict加载到CULane。这两个数据集的输入形状不同。

how can I  do to solve the error? please

**Comment by HejhGitHub** [comment]
> > 似乎您尝试将tusimple模型参数state_dict加载到CULane。这两个数据集的输入形状不同。
> 
> how can I do to solve the error? please

I want to  load tusimple model parameter rather rather than CULane's

**Comment by HejhGitHub** [comment]
I want to load tusimple model to predict the single image,what can I do?

**Comment by harryhan618** [comment]
It is mentioned in Readme.md
```
python test_tusimple.py --exp_dir ./experiments/exp0
```
You should download tusimple model and put it in exp0 folder.

**Comment by harryhan618** [comment]
@HejhGitHub Hello, do you still have any questions? If everything goes fine, I'm going to close the issues.

**Comment by HejhGitHub** [comment]
tangks reply me,IF I want to ask some question in the future,What can I do?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harryhan618/SCNN_Pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 晚上8:49
收件人:&nbsp;"harryhan618/SCNN_Pytorch"<SCNN_Pytorch@noreply.github.com&gt;;
抄送:&nbsp;"HJH"<1499185769@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [harryhan618/SCNN_Pytorch] hello (#54)





 
@HejhGitHub Hello, do you still have any questions? If everything goes fine, I'm going to close the issues.

**Comment by harryhan618** [comment]
You can open a new issue.
