### ISSUE TITLE
excuse me, may I ask you a couple of questions? 

### ISSUE THREAD

**Issue by HejhGitHub** [harryhan618/SCNN_Pytorch#56]
For single image demo test,I used the exp0_best.pth to test the single image,but it show the next errors:
RuntimeError: Error(s) in loading state_dict for SCNN:
        size mismatch for fc.0.weight: copying a param with shape torch.Size([128, 2880]) from checkpoint, the shape in current model is torch.Size([128, 4500]).
How to work out ?

**Comment by harryhan618** [comment]
Are you asking the same question as in issue #54 ?
