### ISSUE TITLE
have you tried SCNN in testing video?

### ISSUE THREAD

**Issue by HITjialanyu** [harryhan618/SCNN_Pytorch#6]
i have a try,0.5s per frame. is it normal?

**Comment by HITjialanyu** [comment]
gpu

**Comment by harryhan618** [comment]
I haven't time the model. But the sequential operation in SCNN may take time.

**Comment by chaotianjiao** [comment]
@HITjialanyu  大佬，我想问下把[demo_test.py](https://github.com/harryhan618/SCNN_Pytorch/blob/master/demo_test.py) 的哪里修改一下就可以检测视频，或者调用摄像头进行检测啊？

**Comment by Chenfy13** [comment]
> @HITjialanyu 大佬，我想问下把[demo_test.py](https://github.com/harryhan618/SCNN_Pytorch/blob/master/demo_test.py) 的哪里修改一下就可以检测视频，或者调用摄像头进行检测啊？

你好，请问你解决了吗
