### ISSUE TITLE
why not use the std and mean values of CULane to do normalization when traing and testing?

### ISSUE THREAD

**Issue by XavierNie715** [harryhan618/SCNN_Pytorch#61]
Thanks for your brilliant job.
I'm little bit confused about the value the code used in normalization, why use std and mean values of imagenet to normalize?

**Comment by harryhan618** [comment]
I think most probably because I'm using imagenet pretrained model weight. It won't cause much difference if you use customed dataset mean and std otherwise, according to my experience.

**Comment by XavierNie715** [comment]
> I think most probably because I'm using imagenet pretrained model weight. It won't cause much difference if you use customed dataset mean and std otherwise, according to my experience.

Thanks very much for your kindly response!
