### ISSUE TITLE
fc_input_feature must be int (?)

### ISSUE THREAD

**Issue by pskugit** [harryhan618/SCNN_Pytorch#9]
Hi, thank you for your implementation :)
I tried to run the demo_test.py but only got it working by changing line 82 in model.py from
`self.fc_input_feature = 5 * input_w/16 * input_h/16`
to
`self.fc_input_feature = int(5 * input_w/16 * input_h/16)`

best regards

**Comment by harryhan618** [comment]
Thank you for the feedback.
